### ISSUE TITLE
renaming this repository: 'awesome-distributed' to 'awesome-distributed-computing-projects'

### ISSUE THREAD

**Issue by ghost** [en3r0/awesome-distributed#4]
Hey y'all, how are you all? 

I would like to suggest some things. I wonder if you all have thought about renaming this repository: 'awesome-distributed' to 'awesome-distributed-computing-projects' so that anyone can easily find this open project.

**note:** The images are illustrative and the image rights are public, but the ui/ux is from GitHub. Please see this:

***img-before***
Here we have the current version **img-before** without any corrections; url-before: `https://github.com/en3r0/awesome-distributed/`
![image](https://github.com/en3r0/awesome-distributed/assets/154566915/38625a75-6d18-4836-97e0-c0986edb77e3)

***img-after***
Here we have the current version **img-after** with any corrections; url-after: `https://github.com/en3r0/awesome-distributed-computing-projects/`
![image](https://github.com/en3r0/awesome-distributed/assets/154566915/d42ab07b-f047-40c2-838a-6d658002168c)

***Have you all thought about renaming this repository: 'awesome-distributed' to 'awesome-distributed-computing-projects' so that anyone can easily find this open project?***

**Comment by en3r0** [comment]
Good idea!

**Comment by ghost** [comment]
Hi @en3r0, thanks!
