### ISSUE TITLE
add the tags to this repo

### ISSUE THREAD

**Issue by ghost** [en3r0/awesome-distributed#5]
Hey y'all, how are you all?

I would like to suggest some things. I'm wondering if you all have thought about adding tags to this repository to make it easier to search on GitHub and Google.

**note:** The images are illustrative and the image rights are public, but the ui/ux is from GitHub.

***img-before: without tags*** |  ***img-after:  with tags: `awesome`, `distributed`, `computing`, `projects`, `foss`, `bitcoin`, `blockchain`, `bittorrent`, `p2p` ...***
:-------------------------:|:-------------------------:
![image](https://github.com/en3r0/awesome-distributed-computing-projects/assets/154566915/ccd85a21-4894-476b-b4e1-7a4f919bf4bf) | ![image](https://github.com/en3r0/awesome-distributed-computing-projects/assets/154566915/a23475e6-8593-4ee9-9eed-51784e33630e)

*why?*
- Would it be possible to add the `#tag-name` tag to this repo I'll show up in this nice list here: `https://github.com/topics/tag-name` i.e `https://github.com/topics/awesome`, `https://github.com/topics/computing` ... 
- makes searching for this repository easier.
- a simple idea so I can contribute even more to this repository
- ease of being done and implemented
- It's just an idea and suggestion that I want to know if it's good or bad, that's why I made an issue (to check the community's opinion about this, about this possibility)

*how?*
This image is illustrative and refers to the UI interface of the fork repository.
![image](https://github.com/en3r0/awesome-distributed-computing-projects/assets/154566915/d8293bfe-a015-4ebe-81e6-6c4a118b504a)

***Have you all thought about adding tags to this repository to make it easier to search on GitHub and Google?***

**Comment by en3r0** [comment]
Good ideas!

**Comment by ghost** [comment]
Hi @en3r0, thanks!
