### ISSUE TITLE
settings in repo

### ISSUE THREAD

**Issue by ghost** [en3r0/awesome-distributed#7]
Hey y'all, how are you all?

I would like to suggest some things. I was thinking about the idea of disabling the repository's release, package and environment options.

**note:** The images are illustrative and the image rights are public, but the ui/ux is from GitHub.

***img-before: with releases, packages, environments*** |  ***img-after:  without releases, packages, environments***
:-------------------------:|:-------------------------:
![image](https://github.com/en3r0/awesome-distributed-computing-projects/assets/154566915/a720bc41-4e78-4eff-a163-803e33f22c57) | ![image](https://github.com/en3r0/awesome-distributed-computing-projects/assets/154566915/d28c8121-d66c-4f26-8d55-5f6076937828)

***settings***
![image](https://github.com/en3r0/awesome-distributed-computing-projects/assets/154566915/89c1bb2a-540a-4eb2-aaea-eb7f86c9517e)

***What do you think of the idea of disabling the repository's release, package, and environment options?***

**Comment by en3r0** [comment]
Good idea!

**Comment by ghost** [comment]
Hi @en3r0, thanks again!
