### ISSUE TITLE
add me as a contributor here?

### ISSUE THREAD

**Issue by ghost** [en3r0/awesome-distributed#8]
Hey y'all, how are you all?

I would like to know if you can add me as a collaborator here. Can you add me as a contributor here?

**img**
The images are illustrative and the image rights are public, but the ui/ux is from GitHub.
![image](https://github.com/en3r0/awesome-distributed-computing-projects/assets/154566915/18aa540e-8b32-43b5-925b-13a72ace5480)

***why?***
- The advantage of being a contributor here is that I can review pull requests from new developers who add links here. 
- Another advantage is that I can help this repository even more, if it is of interest to you and this community.
- I can send pull requests directly without being asked for authorization all the time. 
- Even if I submit a pull request, the repository owner can remove me and go back to the old pull requests.
- What I'm saying is that there is a limitation on what can or cannot be done here, and that even if there is insecurity, everything can be resolved.

***What do you think of the idea of ​​adding me as a contributor here? Does it make sense or not? Can you add me as a contributor here?***

**Comment by en3r0** [comment]
I don't think there are any meaningful limits you are up against without access right now, but maybe in the future.

**Comment by ghost** [comment]
Hi @en3r0, 

> I don't think there are any meaningful limits you are up against without access right now, but maybe in the future.

I didn't understand what you said here, but anyway, thanks for the comment. Have you said in general that you don't like this idea or are you thinking about the future?

**Comment by en3r0** [comment]
In the future if there is a need :)

**Comment by ghost** [comment]
Hi @en3r0, thanks! 

> In the future if there is a need :)

I'm happy today for this great comment.
